"""Add listing_page_snapshot for URL ingest

Revision ID: 5d61ef0d74c5
Revises: 9c6c780ede62
Create Date: 2026-03-28 23:41:08.870209
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5d61ef0d74c5'
down_revision: Union[str, None] = '9c6c780ede62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_page_snapshot',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('source_site', sa.String(length=30), nullable=False, comment='zillow, redfin, realtor'),
    sa.Column('listing_url', sa.String(length=1000), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsed_fields', sqlite.JSON(), nullable=True),
    sa.Column('raw_html_path', sa.String(length=500), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('parser_version', sa.String(length=30), nullable=False, comment='Version of the parser that extracted parsed_fields'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_page_property', 'listing_page_snapshot', ['property_id', 'source_site'], unique=False)
    op.create_index(op.f('ix_listing_page_snapshot_property_id'), 'listing_page_snapshot', ['property_id'], unique=False)
    op.create_index('ix_listing_page_url', 'listing_page_snapshot', ['listing_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_page_url', table_name='listing_page_snapshot')
    op.drop_index(op.f('ix_listing_page_snapshot_property_id'), table_name='listing_page_snapshot')
    op.drop_index('ix_listing_page_property', table_name='listing_page_snapshot')
    op.drop_table('listing_page_snapshot')
    # ### end Alembic commands ###
