"""Phase 0: foundation schema with 20 tables

Revision ID: 6409e32297b2
Revises: 
Create Date: 2026-03-28 19:47:52.309668
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6409e32297b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumption_set',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='reserve_life, replacement_cost, stress_test, scoring_weight, appreciation, financial_defaults'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('values_json', sqlite.JSON(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assumption_set_active', 'assumption_set', ['category', 'active_from'], unique=False)
    op.create_table('data_freshness_policy',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('refresh_priority', sa.Integer(), nullable=False, comment='Higher = refresh first'),
    sa.Column('stale_behavior', sa.String(length=30), nullable=False, comment='warn_only, refresh_before_use, use_cached, require_manual_review'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('source_name', 'entity_type')
    )
    op.create_table('property',
    sa.Column('property_type', sa.String(length=50), nullable=False, comment='single_family, condo, townhouse, multi_family'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_run',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('target_key', sa.String(length=200), nullable=False, comment='e.g., parcel number or address'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('page_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('html_snapshot_path', sa.String(length=500), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_run_source_name'), 'scrape_run', ['source_name'], unique=False)
    op.create_table('source_health',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='healthy, degraded, broken, auth_required, structure_changed'),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=True, comment='DOM structure fingerprint for change detection'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_health_latest', 'source_health', ['source_name', 'checked_at'], unique=False)
    op.create_index(op.f('ix_source_health_source_name'), 'source_health', ['source_name'], unique=False)
    op.create_table('source_registry',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False, comment='official_api, public_arcgis, public_site_scrape, licensed_feed, manual_upload'),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('tos_notes', sa.Text(), nullable=True),
    sa.Column('allowed_use', sa.String(length=200), nullable=True),
    sa.Column('refresh_policy', sa.String(length=200), nullable=True),
    sa.Column('confidence_rank', sa.Integer(), nullable=False, comment='Higher = more trusted. county=90, deed=80, licensed_api=60, listing=40, heuristic=10'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('preferences', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysis_run',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False, comment='financial, appraisal, neighborhood, tax, insurance, investment, condition, hoa, surrounding, offer'),
    sa.Column('ruleset_version', sa.String(length=20), nullable=False, comment='Semantic version of the analysis logic'),
    sa.Column('code_version', sa.String(length=50), nullable=False, comment='Git commit hash or package version'),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False, comment='SHA-256 of the serialized input data — detect data changes'),
    sa.Column('output_json', sqlite.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_run_property', 'analysis_run', ['property_id', 'analysis_type', 'computed_at'], unique=False)
    op.create_index(op.f('ix_analysis_run_property_id'), 'analysis_run', ['property_id'], unique=False)
    op.create_table('buyer_profile',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('payment_comfort', sa.Float(), nullable=True, comment='Max comfortable monthly payment'),
    sa.Column('renovation_tolerance', sa.String(length=20), nullable=True, comment='none, cosmetic, moderate, major'),
    sa.Column('hoa_tolerance', sa.String(length=20), nullable=True, comment='none, low, moderate, high'),
    sa.Column('school_priority', sa.Integer(), nullable=True, comment='1-10'),
    sa.Column('commute_priority', sa.Integer(), nullable=True, comment='1-10'),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True, comment='conservative, moderate, aggressive'),
    sa.Column('hold_period_years', sa.Integer(), nullable=True),
    sa.Column('investment_optionality_weight', sa.Float(), nullable=True, comment='0.0-1.0'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_profile_user_id'), 'buyer_profile', ['user_id'], unique=False)
    op.create_table('parcel',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False, comment='fairfax, loudoun'),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('land_use_code', sa.String(length=20), nullable=True),
    sa.Column('acreage', sa.Float(), nullable=True),
    sa.Column('lot_sqft', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_property_id'), 'parcel', ['property_id'], unique=False)
    op.create_table('property_tag',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'tag_id')
    )
    op.create_table('refresh_job',
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False, comment='county_refresh, listing_monitor, alert_evaluation, source_health_check'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, leased, running, completed, failed, cancelled'),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher = process first'),
    sa.Column('triggered_by', sa.String(length=100), nullable=True, comment='scheduler, user, alert'),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_job_idempotency', 'refresh_job', ['idempotency_key'], unique=True)
    op.create_index('ix_refresh_job_property', 'refresh_job', ['property_id', 'job_type'], unique=False)
    op.create_index('ix_refresh_job_status', 'refresh_job', ['status', 'scheduled_at'], unique=False)
    op.create_table('scoring_profile',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weights_json', sqlite.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_profile_user_id'), 'scoring_profile', ['user_id'], unique=False)
    op.create_table('source_record',
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_payload', sqlite.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_record_property', 'source_record', ['property_id', 'source_name'], unique=False)
    op.create_index(op.f('ix_source_record_property_id'), 'source_record', ['property_id'], unique=False)
    op.create_index(op.f('ix_source_record_source_name'), 'source_record', ['source_name'], unique=False)
    op.create_table('watchlist_entry',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False, comment='researching, touring, offer, contract, closed, rejected'),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_stage', 'watchlist_entry', ['user_id', 'stage'], unique=False)
    op.create_index('ix_watchlist_user_property', 'watchlist_entry', ['user_id', 'property_id'], unique=True)
    op.create_table('address_history',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False, comment='situs, mailing, historical, listing_display'),
    sa.Column('normalized_address', sa.String(length=500), nullable=False),
    sa.Column('raw_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_address_current', 'address_history', ['property_id', 'address_type', 'is_current'], unique=False)
    op.create_index(op.f('ix_address_history_property_id'), 'address_history', ['property_id'], unique=False)
    op.create_table('evidence_item',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False, comment='e.g., year_built, sqft, roof_age'),
    sa.Column('field_value', sa.String(length=500), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False, comment='confirmed, estimated, inferred, unknown'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_item_property_id'), 'evidence_item', ['property_id'], unique=False)
    op.create_index('ix_evidence_property_field', 'evidence_item', ['property_id', 'field_name'], unique=False)
    op.create_table('parcel_event',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='split, merge, renumber, address_change, boundary_adjustment'),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details_json', sqlite.JSON(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_event_property_id'), 'parcel_event', ['property_id'], unique=False)
    op.create_table('parcel_identifier',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('identifier_type', sa.String(length=30), nullable=False, comment='parcel_number, tax_map_number, account_number, GIS_PIN, source_specific_key'),
    sa.Column('identifier_value', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parcel_id_current', 'parcel_identifier', ['county', 'identifier_type', 'identifier_value', 'is_current'], unique=False)
    op.create_index(op.f('ix_parcel_identifier_property_id'), 'parcel_identifier', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_identifier_property_id'), table_name='parcel_identifier')
    op.drop_index('ix_parcel_id_current', table_name='parcel_identifier')
    op.drop_table('parcel_identifier')
    op.drop_index(op.f('ix_parcel_event_property_id'), table_name='parcel_event')
    op.drop_table('parcel_event')
    op.drop_index('ix_evidence_property_field', table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_property_id'), table_name='evidence_item')
    op.drop_table('evidence_item')
    op.drop_index(op.f('ix_address_history_property_id'), table_name='address_history')
    op.drop_index('ix_address_current', table_name='address_history')
    op.drop_table('address_history')
    op.drop_index('ix_watchlist_user_property', table_name='watchlist_entry')
    op.drop_index('ix_watchlist_stage', table_name='watchlist_entry')
    op.drop_table('watchlist_entry')
    op.drop_index(op.f('ix_source_record_source_name'), table_name='source_record')
    op.drop_index(op.f('ix_source_record_property_id'), table_name='source_record')
    op.drop_index('ix_source_record_property', table_name='source_record')
    op.drop_table('source_record')
    op.drop_index(op.f('ix_scoring_profile_user_id'), table_name='scoring_profile')
    op.drop_table('scoring_profile')
    op.drop_index('ix_refresh_job_status', table_name='refresh_job')
    op.drop_index('ix_refresh_job_property', table_name='refresh_job')
    op.drop_index('ix_refresh_job_idempotency', table_name='refresh_job')
    op.drop_table('refresh_job')
    op.drop_table('property_tag')
    op.drop_index(op.f('ix_parcel_property_id'), table_name='parcel')
    op.drop_table('parcel')
    op.drop_index(op.f('ix_buyer_profile_user_id'), table_name='buyer_profile')
    op.drop_table('buyer_profile')
    op.drop_index(op.f('ix_analysis_run_property_id'), table_name='analysis_run')
    op.drop_index('ix_analysis_run_property', table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_source_health_source_name'), table_name='source_health')
    op.drop_index('ix_source_health_latest', table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_scrape_run_source_name'), table_name='scrape_run')
    op.drop_table('scrape_run')
    op.drop_table('property')
    op.drop_table('data_freshness_policy')
    op.drop_index('ix_assumption_set_active', table_name='assumption_set')
    op.drop_table('assumption_set')
    # ### end Alembic commands ###
