"""Add decision workflow layer

Revision ID: 7b26660914f8
Revises: 5d61ef0d74c5
Create Date: 2026-03-29 01:54:26.185722
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7b26660914f8'
down_revision: Union[str, None] = '5d61ef0d74c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_case',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False, comment='discovered, shortlisted, touring, researching, waiting_on_docs, offer_ready, offered, passed, lost, won'),
    sa.Column('decision_status', sa.String(length=20), nullable=False, comment='pursue, maybe, deprioritize, reject'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1-10'),
    sa.Column('pursue_score', sa.Float(), nullable=True, comment='0-100 computed score'),
    sa.Column('max_offer_current', sa.Float(), nullable=True),
    sa.Column('walk_away_price', sa.Float(), nullable=True),
    sa.Column('target_monthly_payment', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=10), nullable=True, comment='high, medium, low'),
    sa.Column('status_summary', sa.Text(), nullable=True),
    sa.Column('offer_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spouse_notes', sa.Text(), nullable=True),
    sa.Column('family_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_case_property', 'decision_case', ['property_id'], unique=False)
    op.create_index(op.f('ix_decision_case_property_id'), 'decision_case', ['property_id'], unique=True)
    op.create_index('ix_decision_case_stage', 'decision_case', ['stage', 'decision_status'], unique=False)
    op.create_table('due_diligence_item',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('decision_case_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False, comment='hoa, permit, inspection, financing, insurance, legal, seller_question, agent_question, general'),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='open, requested, received, resolved, blocked'),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='critical, important, minor, info'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True, comment='Link to uploaded document if resolved with a doc'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_case_id'], ['decision_case.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dd_item_case', 'due_diligence_item', ['decision_case_id'], unique=False)
    op.create_index('ix_dd_item_property', 'due_diligence_item', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_due_diligence_item_property_id'), 'due_diligence_item', ['property_id'], unique=False)
    op.create_table('recommendation_snapshot',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('decision_case_id', sa.String(length=36), nullable=True),
    sa.Column('pursue_recommendation', sa.String(length=10), nullable=False, comment='pursue, maybe, pass'),
    sa.Column('max_offer', sa.Float(), nullable=True),
    sa.Column('walk_away_price', sa.Float(), nullable=True),
    sa.Column('main_red_flags', sqlite.JSON(), nullable=True, comment='List of red-flag strings'),
    sa.Column('unresolved_unknowns', sqlite.JSON(), nullable=True, comment='List of unknown strings'),
    sa.Column('top_questions', sqlite.JSON(), nullable=True, comment='List of questions for agent/inspector'),
    sa.Column('compare_rank', sa.Integer(), nullable=True, comment='Rank among current shortlist'),
    sa.Column('analysis_run_ids', sqlite.JSON(), nullable=True, comment='List of analysis_run IDs that fed this'),
    sa.Column('confidence', sa.String(length=10), nullable=False, comment='high, medium, low'),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_case_id'], ['decision_case.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_case', 'recommendation_snapshot', ['decision_case_id'], unique=False)
    op.create_index('ix_recommendation_property', 'recommendation_snapshot', ['property_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_snapshot_property_id'), 'recommendation_snapshot', ['property_id'], unique=False)
    op.add_column('listing_page_snapshot', sa.Column('canonical_listing_key', sa.String(length=200), nullable=True, comment='Cross-site canonical key, e.g. zillow:251682872'))
    op.add_column('listing_page_snapshot', sa.Column('site_listing_id', sa.String(length=200), nullable=True, comment='Site-specific listing ID, e.g. 251682872_zpid'))
    op.add_column('listing_page_snapshot', sa.Column('scrape_success', sa.Boolean(), nullable=False))
    op.add_column('listing_page_snapshot', sa.Column('parser_strategy_used', sa.String(length=30), nullable=True, comment='graphql, jsonld, dom, mixed'))
    op.add_column('listing_page_snapshot', sa.Column('parse_warnings', sqlite.JSON(), nullable=True, comment='List of warning strings from the parser'))
    op.add_column('listing_page_snapshot', sa.Column('html_hash', sa.String(length=64), nullable=True, comment='Hash of saved HTML for change detection'))
    op.add_column('listing_page_snapshot', sa.Column('extracted_at_version', sa.String(length=30), nullable=True, comment='Parser version at extraction time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_page_snapshot', 'extracted_at_version')
    op.drop_column('listing_page_snapshot', 'html_hash')
    op.drop_column('listing_page_snapshot', 'parse_warnings')
    op.drop_column('listing_page_snapshot', 'parser_strategy_used')
    op.drop_column('listing_page_snapshot', 'scrape_success')
    op.drop_column('listing_page_snapshot', 'site_listing_id')
    op.drop_column('listing_page_snapshot', 'canonical_listing_key')
    op.drop_index(op.f('ix_recommendation_snapshot_property_id'), table_name='recommendation_snapshot')
    op.drop_index('ix_recommendation_property', table_name='recommendation_snapshot')
    op.drop_index('ix_recommendation_case', table_name='recommendation_snapshot')
    op.drop_table('recommendation_snapshot')
    op.drop_index(op.f('ix_due_diligence_item_property_id'), table_name='due_diligence_item')
    op.drop_index('ix_dd_item_property', table_name='due_diligence_item')
    op.drop_index('ix_dd_item_case', table_name='due_diligence_item')
    op.drop_table('due_diligence_item')
    op.drop_index('ix_decision_case_stage', table_name='decision_case')
    op.drop_index(op.f('ix_decision_case_property_id'), table_name='decision_case')
    op.drop_index('ix_decision_case_property', table_name='decision_case')
    op.drop_table('decision_case')
    # ### end Alembic commands ###
