"""Add all Phase 1-7 tables

Revision ID: 9c6c780ede62
Revises: 6409e32297b2
Create Date: 2026-03-28 22:17:05.053135
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9c6c780ede62'
down_revision: Union[str, None] = '6409e32297b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_event',
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='info, warning, critical'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_event_property_id'), 'alert_event', ['property_id'], unique=False)
    op.create_table('alert_subscription',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('filter_criteria', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_subscription_user_id'), 'alert_subscription', ['user_id'], unique=False)
    op.create_table('component_system',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.String(length=30), nullable=False, comment='roof, hvac, water_heater, electrical_panel, plumbing, windows, siding, foundation, deck, appliances, drainage'),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('estimated_install_year', sa.Integer(), nullable=True),
    sa.Column('expected_lifespan', sa.Integer(), nullable=True),
    sa.Column('estimated_replacement_cost', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False, comment='confirmed, estimated, unknown'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_component_property_type', 'component_system', ['property_id', 'component_type'], unique=False)
    op.create_index(op.f('ix_component_system_property_id'), 'component_system', ['property_id'], unique=False)
    op.create_table('development_case',
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('applicant', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distance_feet', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('hearing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_case_property_id'), 'development_case', ['property_id'], unique=False)
    op.create_table('document',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False, comment='inspection, disclosure, appraisal, contract, hoa_ccr, other'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_property_id'), 'document', ['property_id'], unique=False)
    op.create_table('hazard_profile',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('flood_zone', sa.String(length=20), nullable=True),
    sa.Column('flood_risk_score', sa.Float(), nullable=True),
    sa.Column('radon_zone', sa.String(length=10), nullable=True),
    sa.Column('radon_risk', sa.Float(), nullable=True),
    sa.Column('wildfire_risk', sa.Float(), nullable=True),
    sa.Column('earthquake_risk', sa.Float(), nullable=True),
    sa.Column('hurricane_risk', sa.Float(), nullable=True),
    sa.Column('tornado_risk', sa.Float(), nullable=True),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('nri_data', sqlite.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_profile_property_id'), 'hazard_profile', ['property_id'], unique=True)
    op.create_table('insurance_quote',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('annual_premium', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=True),
    sa.Column('coverage_amount', sa.Float(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_quote_property_id'), 'insurance_quote', ['property_id'], unique=False)
    op.create_table('listing_episode',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('original_list_price', sa.Float(), nullable=True),
    sa.Column('original_list_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment='active, pending, sold, withdrawn, expired'),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('mls_number', sa.String(length=50), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_episode_property', 'listing_episode', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_listing_episode_property_id'), 'listing_episode', ['property_id'], unique=False)
    op.create_table('mortgage_quote',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('apr', sa.Float(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=False, comment='Loan term in months'),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('down_payment_pct', sa.Float(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('closing_cost', sa.Float(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mortgage_quote_property_id'), 'mortgage_quote', ['property_id'], unique=False)
    op.create_table('nearby_relationship',
    sa.Column('subject_property_id', sa.String(length=36), nullable=False),
    sa.Column('related_property_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False, comment='adjacent, same_street, same_subdivision, same_HOA, within_250ft, within_500ft, same_school_zone, same_builder_cluster'),
    sa.Column('distance_feet', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['subject_property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nearby_relationship_related_property_id'), 'nearby_relationship', ['related_property_id'], unique=False)
    op.create_index(op.f('ix_nearby_relationship_subject_property_id'), 'nearby_relationship', ['subject_property_id'], unique=False)
    op.create_index('ix_nearby_subject_type', 'nearby_relationship', ['subject_property_id', 'relationship_type'], unique=False)
    op.create_table('permit_record',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('contractor', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permit_property_type', 'permit_record', ['property_id', 'type'], unique=False)
    op.create_index(op.f('ix_permit_record_property_id'), 'permit_record', ['property_id'], unique=False)
    op.create_table('photo_asset',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_asset_property_id'), 'photo_asset', ['property_id'], unique=False)
    op.create_table('property_note',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False, comment='general, showing, concern, positive'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_note_property_id'), 'property_note', ['property_id'], unique=False)
    op.create_table('repair_estimate',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_low', sa.Float(), nullable=False),
    sa.Column('cost_mid', sa.Float(), nullable=False),
    sa.Column('cost_high', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False, comment='immediate, 1_year, 3_year, 5_year'),
    sa.Column('contractor', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_estimate_property_id'), 'repair_estimate', ['property_id'], unique=False)
    op.create_table('sale_event',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_event_property_id'), 'sale_event', ['property_id'], unique=False)
    op.create_table('zoning_case',
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('applicant', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('hearing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoning_case_property_id'), 'zoning_case', ['property_id'], unique=False)
    op.create_table('zoning_record',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('zone_code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('overlay_districts', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoning_record_property_id'), 'zoning_record', ['property_id'], unique=False)
    op.create_table('assessment_snapshot',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('land_value', sa.Float(), nullable=False),
    sa.Column('improvement_value', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('annual_tax', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_property_year', 'assessment_snapshot', ['property_id', 'tax_year'], unique=False)
    op.create_index(op.f('ix_assessment_snapshot_property_id'), 'assessment_snapshot', ['property_id'], unique=False)
    op.create_table('community',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('community_type', sa.String(length=30), nullable=False, comment='HOA, condo, coop, civic_association'),
    sa.Column('management_company', sa.String(length=200), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_evidence',
    sa.Column('component_system_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False, comment='permit, inspection, disclosure, listing, user'),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_value', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_system_id'], ['component_system.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_evidence_component_system_id'), 'component_evidence', ['component_system_id'], unique=False)
    op.create_table('deed_record',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('grantor', sa.String(length=500), nullable=True),
    sa.Column('grantee', sa.String(length=500), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deed_type', sa.String(length=50), nullable=True),
    sa.Column('instrument_number', sa.String(length=100), nullable=True),
    sa.Column('recorded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deed_property_date', 'deed_record', ['property_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_deed_record_property_id'), 'deed_record', ['property_id'], unique=False)
    op.create_table('extracted_fact',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('fact_type', sa.String(length=100), nullable=False),
    sa.Column('fact_value_text', sa.String(length=500), nullable=True),
    sa.Column('fact_value_number', sa.Float(), nullable=True),
    sa.Column('fact_value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False, comment='confirmed, estimated, inferred, unknown'),
    sa.Column('page_ref', sa.String(length=50), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('normalized_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fact_document_id'), 'extracted_fact', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fact_property_id'), 'extracted_fact', ['property_id'], unique=False)
    op.create_index('ix_fact_property_type', 'extracted_fact', ['property_id', 'fact_type'], unique=False)
    op.create_table('geometry_snapshot',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('geometry_type', sa.String(length=30), nullable=False, comment='parcel_boundary, building_footprint, address_point, lot_outline'),
    sa.Column('geometry_format', sa.String(length=10), nullable=False, comment='geojson, wkt'),
    sa.Column('geometry_data', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geometry_property_type', 'geometry_snapshot', ['property_id', 'geometry_type'], unique=False)
    op.create_index(op.f('ix_geometry_snapshot_property_id'), 'geometry_snapshot', ['property_id'], unique=False)
    op.create_table('listing_snapshot',
    sa.Column('listing_episode_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delta_price', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_episode_id'], ['listing_episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_snapshot_listing_episode_id'), 'listing_snapshot', ['listing_episode_id'], unique=False)
    op.create_table('overlay_intersection',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('overlay_type', sa.String(length=30), nullable=False, comment='floodplain, watershed, easement, utility_corridor, airport_noise, soil_class, slope_band, zoning_overlay'),
    sa.Column('intersects', sa.Boolean(), nullable=False),
    sa.Column('overlap_pct', sa.Float(), nullable=True),
    sa.Column('overlay_value_json', sqlite.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overlay_intersection_property_id'), 'overlay_intersection', ['property_id'], unique=False)
    op.create_index('ix_overlay_property_type', 'overlay_intersection', ['property_id', 'overlay_type'], unique=False)
    op.create_table('plat_record',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('plat_number', sa.String(length=100), nullable=True),
    sa.Column('subdivision_name', sa.String(length=200), nullable=True),
    sa.Column('recorded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_page', sa.String(length=50), nullable=True),
    sa.Column('easement_notes', sa.Text(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plat_record_property_id'), 'plat_record', ['property_id'], unique=False)
    op.create_table('price_event',
    sa.Column('listing_episode_id', sa.String(length=36), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_episode_id'], ['listing_episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_event_listing_episode_id'), 'price_event', ['listing_episode_id'], unique=False)
    op.create_table('status_event',
    sa.Column('listing_episode_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_episode_id'], ['listing_episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_event_listing_episode_id'), 'status_event', ['listing_episode_id'], unique=False)
    op.create_table('community_amenity',
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('amenity_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_amenity_community_id'), 'community_amenity', ['community_id'], unique=False)
    op.create_table('hoa_document',
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hoa_document_community_id'), 'hoa_document', ['community_id'], unique=False)
    op.create_table('hoa_fee_history',
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('special_assessment', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hoa_fee_community_date', 'hoa_fee_history', ['community_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_hoa_fee_history_community_id'), 'hoa_fee_history', ['community_id'], unique=False)
    op.create_table('hoa_financial_snapshot',
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('reserve_balance', sa.Float(), nullable=True),
    sa.Column('reserve_pct_funded', sa.Float(), nullable=True),
    sa.Column('delinquency_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hoa_fin_community_year', 'hoa_financial_snapshot', ['community_id', 'fiscal_year'], unique=False)
    op.create_index(op.f('ix_hoa_financial_snapshot_community_id'), 'hoa_financial_snapshot', ['community_id'], unique=False)
    op.create_table('hoa_rule',
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('restriction_level', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hoa_rule_community_id'), 'hoa_rule', ['community_id'], unique=False)
    op.create_table('property_community_membership',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('membership_type', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pcm_property_community', 'property_community_membership', ['property_id', 'community_id'], unique=False)
    op.create_index(op.f('ix_property_community_membership_community_id'), 'property_community_membership', ['community_id'], unique=False)
    op.create_index(op.f('ix_property_community_membership_property_id'), 'property_community_membership', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_community_membership_property_id'), table_name='property_community_membership')
    op.drop_index(op.f('ix_property_community_membership_community_id'), table_name='property_community_membership')
    op.drop_index('ix_pcm_property_community', table_name='property_community_membership')
    op.drop_table('property_community_membership')
    op.drop_index(op.f('ix_hoa_rule_community_id'), table_name='hoa_rule')
    op.drop_table('hoa_rule')
    op.drop_index(op.f('ix_hoa_financial_snapshot_community_id'), table_name='hoa_financial_snapshot')
    op.drop_index('ix_hoa_fin_community_year', table_name='hoa_financial_snapshot')
    op.drop_table('hoa_financial_snapshot')
    op.drop_index(op.f('ix_hoa_fee_history_community_id'), table_name='hoa_fee_history')
    op.drop_index('ix_hoa_fee_community_date', table_name='hoa_fee_history')
    op.drop_table('hoa_fee_history')
    op.drop_index(op.f('ix_hoa_document_community_id'), table_name='hoa_document')
    op.drop_table('hoa_document')
    op.drop_index(op.f('ix_community_amenity_community_id'), table_name='community_amenity')
    op.drop_table('community_amenity')
    op.drop_index(op.f('ix_status_event_listing_episode_id'), table_name='status_event')
    op.drop_table('status_event')
    op.drop_index(op.f('ix_price_event_listing_episode_id'), table_name='price_event')
    op.drop_table('price_event')
    op.drop_index(op.f('ix_plat_record_property_id'), table_name='plat_record')
    op.drop_table('plat_record')
    op.drop_index('ix_overlay_property_type', table_name='overlay_intersection')
    op.drop_index(op.f('ix_overlay_intersection_property_id'), table_name='overlay_intersection')
    op.drop_table('overlay_intersection')
    op.drop_index(op.f('ix_listing_snapshot_listing_episode_id'), table_name='listing_snapshot')
    op.drop_table('listing_snapshot')
    op.drop_index(op.f('ix_geometry_snapshot_property_id'), table_name='geometry_snapshot')
    op.drop_index('ix_geometry_property_type', table_name='geometry_snapshot')
    op.drop_table('geometry_snapshot')
    op.drop_index('ix_fact_property_type', table_name='extracted_fact')
    op.drop_index(op.f('ix_extracted_fact_property_id'), table_name='extracted_fact')
    op.drop_index(op.f('ix_extracted_fact_document_id'), table_name='extracted_fact')
    op.drop_table('extracted_fact')
    op.drop_index(op.f('ix_deed_record_property_id'), table_name='deed_record')
    op.drop_index('ix_deed_property_date', table_name='deed_record')
    op.drop_table('deed_record')
    op.drop_index(op.f('ix_component_evidence_component_system_id'), table_name='component_evidence')
    op.drop_table('component_evidence')
    op.drop_table('community')
    op.drop_index(op.f('ix_assessment_snapshot_property_id'), table_name='assessment_snapshot')
    op.drop_index('ix_assessment_property_year', table_name='assessment_snapshot')
    op.drop_table('assessment_snapshot')
    op.drop_index(op.f('ix_zoning_record_property_id'), table_name='zoning_record')
    op.drop_table('zoning_record')
    op.drop_index(op.f('ix_zoning_case_property_id'), table_name='zoning_case')
    op.drop_table('zoning_case')
    op.drop_index(op.f('ix_sale_event_property_id'), table_name='sale_event')
    op.drop_table('sale_event')
    op.drop_index(op.f('ix_repair_estimate_property_id'), table_name='repair_estimate')
    op.drop_table('repair_estimate')
    op.drop_index(op.f('ix_property_note_property_id'), table_name='property_note')
    op.drop_table('property_note')
    op.drop_index(op.f('ix_photo_asset_property_id'), table_name='photo_asset')
    op.drop_table('photo_asset')
    op.drop_index(op.f('ix_permit_record_property_id'), table_name='permit_record')
    op.drop_index('ix_permit_property_type', table_name='permit_record')
    op.drop_table('permit_record')
    op.drop_index('ix_nearby_subject_type', table_name='nearby_relationship')
    op.drop_index(op.f('ix_nearby_relationship_subject_property_id'), table_name='nearby_relationship')
    op.drop_index(op.f('ix_nearby_relationship_related_property_id'), table_name='nearby_relationship')
    op.drop_table('nearby_relationship')
    op.drop_index(op.f('ix_mortgage_quote_property_id'), table_name='mortgage_quote')
    op.drop_table('mortgage_quote')
    op.drop_index(op.f('ix_listing_episode_property_id'), table_name='listing_episode')
    op.drop_index('ix_listing_episode_property', table_name='listing_episode')
    op.drop_table('listing_episode')
    op.drop_index(op.f('ix_insurance_quote_property_id'), table_name='insurance_quote')
    op.drop_table('insurance_quote')
    op.drop_index(op.f('ix_hazard_profile_property_id'), table_name='hazard_profile')
    op.drop_table('hazard_profile')
    op.drop_index(op.f('ix_document_property_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_development_case_property_id'), table_name='development_case')
    op.drop_table('development_case')
    op.drop_index(op.f('ix_component_system_property_id'), table_name='component_system')
    op.drop_index('ix_component_property_type', table_name='component_system')
    op.drop_table('component_system')
    op.drop_index(op.f('ix_alert_subscription_user_id'), table_name='alert_subscription')
    op.drop_table('alert_subscription')
    op.drop_index(op.f('ix_alert_event_property_id'), table_name='alert_event')
    op.drop_table('alert_event')
    # ### end Alembic commands ###
