"""Add pipeline run model

Revision ID: c3cc75fb4f71
Revises: 7b26660914f8
Create Date: 2026-03-29 05:16:24.861973
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c3cc75fb4f71'
down_revision: Union[str, None] = '7b26660914f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False, comment='quick_ingest, full_pipeline, refresh_zillow, refresh_county, run_deep_comp, rerun_ai, rerun_financials'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued, running, partial_success, succeeded, failed, cancelled'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', sa.String(length=20), nullable=False, comment='user, scheduler, system'),
    sa.Column('summary_json', sqlite.JSON(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_run_property', 'pipeline_run', ['property_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_property_id'), 'pipeline_run', ['property_id'], unique=False)
    op.create_index('ix_pipeline_run_status', 'pipeline_run', ['status'], unique=False)
    op.create_table('pipeline_task_run',
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False, comment='zillow_scrape, county_scrape, ai_pass_1, resolver, financial, tax, condition, offer, stress, warning_engine, ai_pass_2, decision_packet, school_lookup, comp_quick, comp_deep'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, running, succeeded, failed, skipped'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('result_summary', sqlite.JSON(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_task_run_pipeline_run_id'), 'pipeline_task_run', ['pipeline_run_id'], unique=False)
    op.create_index('ix_pipeline_task_run_run', 'pipeline_task_run', ['pipeline_run_id', 'task_name'], unique=False)
    op.create_index('ix_pipeline_task_run_status', 'pipeline_task_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_task_run_status', table_name='pipeline_task_run')
    op.drop_index('ix_pipeline_task_run_run', table_name='pipeline_task_run')
    op.drop_index(op.f('ix_pipeline_task_run_pipeline_run_id'), table_name='pipeline_task_run')
    op.drop_table('pipeline_task_run')
    op.drop_index('ix_pipeline_run_status', table_name='pipeline_run')
    op.drop_index(op.f('ix_pipeline_run_property_id'), table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_property', table_name='pipeline_run')
    op.drop_table('pipeline_run')
    # ### end Alembic commands ###
